# Default values for kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/padok-training-lab/bam-stack-api
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000

db:
  address: padok-training-lab:europe-west4:rpx-test-database-05
  port: 5432
  name: bam_stack_api
  user: docker
  password: docker

api:
  port: 3000

firebase:
  key: firebase-adminsdk.json
