apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system

---
# rbac: Role-Based Access Control
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller-clusterrolebinding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
