apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bam-stack-api.fullname" . }}
  labels:
{{ include "bam-stack-api.labels" . | indent 4 }}
data:
  parameters.yml.dist: |

    listen_port: {{ .Values.api.port }}
    cors_origin: false
    
    database:
      host: localhost
      port: 5432
      database: {{ .Values.db.name }}
      username: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    
    cheat_bearer: null
    
    firebase:
      service_account_path: './config/{{ .Values.firebase.key  }}'
    
    apollo:
      playground: true
      introspection: true
      engine_api_key: false
