apiVersion: v1
kind: Service
metadata:
  name: {{ include "bam-stack-api.fullname" . }}
  labels:
{{ include "bam-stack-api.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-node
      port: {{ .Values.service.port }}
      targetPort: node-port
      procotol: TCP
  selector:
    # TODO Ask for the aim of these tags
    app.bam-stack-api.io/name: {{ include "bam-stack-api.fullname" . }}
    app.bam-stack-api.io/instance: {{ .Release.Name }}
